import { createClient } from "@/lib/supabase/client";
import { lojaAtivaId } from "@/lib/loja-ativa";

export type SolicitacaoPortal={id:string;tipo:string;titulo:string;descricao:string;status:string;resposta:string;criadoEm:string;obreiroId:string;dados:Record<string,unknown>};
export type ComunicadoPortal={id:string;titulo:string;mensagem:string;tipo:string;prioridade:string;publicoAlvo:string;status:string;publicadoEm:string;expiraEm:string};

async function contexto(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão expirada. Entre novamente.");const preferida=lojaAtivaId();let q=supabase.from("loja_usuarios").select("loja_id,perfil,obreiro_id,acesso_portal_obreiro").eq("usuario_id",user.id).eq("status","ativo");if(preferida)q=q.eq("loja_id",preferida);const{data:vinculo}=await q.limit(1).single();if(!vinculo)throw new Error("Seu usuário ainda não está vinculado a uma Loja.");if(!vinculo.acesso_portal_obreiro)throw new Error("O acesso ao Portal não está liberado para esta Loja.");if(!vinculo.obreiro_id)throw new Error("Vincule um Obreiro antes de acessar o Portal.");return{supabase,user,perfil:{perfil:vinculo.perfil,obreiro_id:vinculo.obreiro_id},lojaId:vinculo.loja_id,obreiroId:vinculo.obreiro_id};}

export async function carregarPortal(){const c=await contexto();if(!c.obreiroId)return{...c,obreiro:null,presencas:[],mensalidades:[],recebimentos:[],agenda:[],documentos:[],comunicados:[],solicitacoes:[]};const[o,p,m,r,a,d,co,s]=await Promise.all([
 c.supabase.from("obreiros").select("*").eq("id",c.obreiroId).maybeSingle(),
 c.supabase.from("presencas").select("*,sessoes(data,tipo,titulo)").eq("obreiro_id",c.obreiroId),
 c.supabase.from("mensalidades").select("*").eq("obreiro_id",c.obreiroId).order("competencia",{ascending:false}),
 c.supabase.from("recebimentos").select("*").eq("obreiro_id",c.obreiroId).order("data",{ascending:false}),
 c.supabase.from("agenda_eventos").select("*").eq("loja_id",c.lojaId).order("inicio"),
 c.supabase.from("documentos_gestao").select("*").eq("loja_id",c.lojaId).order("data_documento",{ascending:false}),
 c.supabase.from("comunicados_internos").select("*").eq("loja_id",c.lojaId).order("publicado_em",{ascending:false}),
 c.supabase.from("solicitacoes_obreiro").select("*").eq("usuario_id",c.user.id).order("criado_em",{ascending:false})]);
 for(const x of[o,p,m,r,a,d,co,s])if(x.error)throw new Error("Não foi possível carregar todas as informações do Portal.");
 return{...c,obreiro:o.data,presencas:p.data??[],mensalidades:m.data??[],recebimentos:r.data??[],agenda:a.data??[],documentos:d.data??[],comunicados:co.data??[],solicitacoes:(s.data??[]).map(i=>({id:i.id,tipo:i.tipo,titulo:i.titulo,descricao:i.descricao,status:i.status,resposta:i.resposta??"",criadoEm:i.criado_em,obreiroId:i.obreiro_id,dados:i.dados_json??{}}))};
}
export async function criarSolicitacao(input:{tipo:string;titulo:string;descricao:string;dados?:Record<string,unknown>}){const c=await contexto();if(!c.obreiroId)throw new Error("Seu usuário ainda não está vinculado ao cadastro de Obreiro.");const{error}=await c.supabase.from("solicitacoes_obreiro").insert({loja_id:c.lojaId,obreiro_id:c.obreiroId,usuario_id:c.user.id,tipo:input.tipo,titulo:input.titulo.trim(),descricao:input.descricao.trim(),dados_json:input.dados??{}});if(error)throw new Error(error.message);}
export async function listarComunicados():Promise<ComunicadoPortal[]>{const c=await contexto();const{data,error}=await c.supabase.from("comunicados_internos").select("*").eq("loja_id",c.lojaId).order("criado_em",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(i=>({id:i.id,titulo:i.titulo,mensagem:i.mensagem,tipo:i.tipo,prioridade:i.prioridade,publicoAlvo:i.publico_alvo,status:i.status,publicadoEm:i.publicado_em??"",expiraEm:i.expira_em??""}));}
export async function salvarComunicado(i:ComunicadoPortal){const c=await contexto();const p={loja_id:c.lojaId,titulo:i.titulo.trim(),mensagem:i.mensagem.trim(),tipo:i.tipo,prioridade:i.prioridade,publico_alvo:i.publicoAlvo,status:i.status,publicado_em:i.status==="Publicado"?(i.publicadoEm||new Date().toISOString()):null,expira_em:i.expiraEm||null};const q=i.id?c.supabase.from("comunicados_internos").update(p).eq("id",i.id):c.supabase.from("comunicados_internos").insert(p);const{error}=await q;if(error)throw new Error(error.message);}
export async function listarSolicitacoesAdministrativas():Promise<SolicitacaoPortal[]>{const c=await contexto();const{data,error}=await c.supabase.from("solicitacoes_obreiro").select("*").eq("loja_id",c.lojaId).order("criado_em",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(i=>({id:i.id,tipo:i.tipo,titulo:i.titulo,descricao:i.descricao,status:i.status,resposta:i.resposta??"",criadoEm:i.criado_em,obreiroId:i.obreiro_id,dados:i.dados_json??{}}));}
export async function responderSolicitacao(id:string,status:string,resposta:string){const c=await contexto();const{error}=await c.supabase.from("solicitacoes_obreiro").update({status,resposta:resposta.trim()||null,respondido_em:new Date().toISOString()}).eq("id",id).eq("loja_id",c.lojaId);if(error)throw new Error(error.message);}
