"use client";
import { FormEvent, useEffect, useState } from "react";
import { EmptyState, Feedback, LoadingState } from "@/components/ui/Feedback";
import { FormField } from "@/components/ui/FormField";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { carregarCadastrosFinanceiros, excluirCadastroFinanceiro, salvarCategoriaFinanceira, salvarCentroCusto, salvarContaFinanceira, type CadastrosFinanceiros, type CategoriaFinanceira, type CentroCusto, type ContaFinanceira } from "@/lib/supabase/operacional";

const campo="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3";
const contaVazia:ContaFinanceira={id:"",nome:"",tipo:"Conta corrente",banco:"",agencia:"",numero:"",saldoInicial:0,ativa:true};
const categoriaVazia:CategoriaFinanceira={id:"",nome:"",natureza:"Receita",cor:"#fbbf24",ativa:true};
const centroVazio:CentroCusto={id:"",nome:"",descricao:"",ativo:true};
export function ConfiguracoesFinanceirasClient(){
 const [dados,setDados]=useState<CadastrosFinanceiros>({contas:[],categorias:[],centros:[]}); const [aba,setAba]=useState<"Contas"|"Categorias"|"Centros de custo">("Contas"); const [conta,setConta]=useState(contaVazia); const [categoria,setCategoria]=useState(categoriaVazia); const [centro,setCentro]=useState(centroVazio); const [carregando,setCarregando]=useState(true); const [salvando,setSalvando]=useState(false); const [erro,setErro]=useState(""); const [sucesso,setSucesso]=useState(""); const [exclusao,setExclusao]=useState<{tabela:"contas_financeiras"|"categorias_financeiras"|"centros_custo";id:string;nome:string}|null>(null);
 useEffect(()=>{carregarCadastrosFinanceiros().then(setDados).catch((e:unknown)=>setErro(e instanceof Error?e.message:"Não foi possível carregar os cadastros financeiros.")).finally(()=>setCarregando(false));},[]);
 async function executar<T>(acao:()=>Promise<T>,aoSalvar:(valor:T)=>void,mensagem:string){setSalvando(true);setErro("");setSucesso("");try{aoSalvar(await acao());setSucesso(mensagem);}catch(e){setErro(e instanceof Error?e.message:"Não foi possível concluir a operação.");}finally{setSalvando(false);}}
 function salvarConta(e:FormEvent){e.preventDefault();if(!conta.nome.trim())return setErro("Informe o nome da conta.");void executar(()=>salvarContaFinanceira(conta),(salva)=>{setDados(d=>({...d,contas:conta.id?d.contas.map(i=>i.id===conta.id?salva:i):[...d.contas,salva]}));setConta(contaVazia);},"Conta financeira salva.");}
 function salvarCategoria(e:FormEvent){e.preventDefault();if(!categoria.nome.trim())return setErro("Informe o nome da categoria.");void executar(()=>salvarCategoriaFinanceira(categoria),(salva)=>{setDados(d=>({...d,categorias:categoria.id?d.categorias.map(i=>i.id===categoria.id?salva:i):[...d.categorias,salva]}));setCategoria(categoriaVazia);},"Categoria salva.");}
 function salvarCentro(e:FormEvent){e.preventDefault();if(!centro.nome.trim())return setErro("Informe o nome do centro de custo.");void executar(()=>salvarCentroCusto(centro),(salvo)=>{setDados(d=>({...d,centros:centro.id?d.centros.map(i=>i.id===centro.id?salvo:i):[...d.centros,salvo]}));setCentro(centroVazio);},"Centro de custo salvo.");}
 async function remover(){if(!exclusao)return;const alvo=exclusao;setExclusao(null);try{await excluirCadastroFinanceiro(alvo.tabela,alvo.id);setDados(d=>({...d,contas:alvo.tabela==="contas_financeiras"?d.contas.filter(i=>i.id!==alvo.id):d.contas,categorias:alvo.tabela==="categorias_financeiras"?d.categorias.filter(i=>i.id!==alvo.id):d.categorias,centros:alvo.tabela==="centros_custo"?d.centros.filter(i=>i.id!==alvo.id):d.centros}));setSucesso("Cadastro removido.");}catch(e){setErro(e instanceof Error?e.message:"Não foi possível remover. Verifique se existem lançamentos vinculados.");}}
 if(carregando)return <div className="mt-8"><LoadingState label="Carregando configuração financeira…"/></div>;
 return <div className="mt-8 space-y-6">{erro&&<Feedback tone="error">{erro.includes("contas_financeiras")?"A migration da Tesouraria profissional ainda não foi aplicada. Execute 20260717_professional_treasury.sql no Supabase.":erro}</Feedback>}{sucesso&&<Feedback tone="success">{sucesso}</Feedback>}
 <section className="grid gap-4 sm:grid-cols-3">{[["Contas",dados.contas.length],["Categorias",dados.categorias.length],["Centros de custo",dados.centros.length]].map(([t,v])=><article key={String(t)} className="sigma-surface rounded-3xl p-5"><p className="text-sm text-zinc-400">{t}</p><p className="mt-2 text-3xl font-black text-amber-300">{v}</p></article>)}</section>
 <section className="sigma-surface rounded-3xl p-4 sm:p-6"><div className="flex flex-wrap gap-2" role="tablist">{(["Contas","Categorias","Centros de custo"] as const).map(item=><button key={item} role="tab" aria-selected={aba===item} onClick={()=>setAba(item)} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${aba===item?"bg-amber-400 text-black":"border border-white/10 text-zinc-300"}`}>{item}</button>)}</div>
 {aba==="Contas"&&<div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={salvarConta} className="rounded-2xl border border-white/10 bg-black/15 p-5"><h2 className="text-xl font-bold">{conta.id?"Editar conta":"Nova conta"}</h2><div className="mt-5 space-y-4"><FormField id="conta-nome" label="Nome" required><input id="conta-nome" value={conta.nome} onChange={e=>setConta({...conta,nome:e.target.value})} placeholder="Ex.: Caixa da Loja" className={campo}/></FormField><FormField id="conta-tipo" label="Tipo"><select id="conta-tipo" value={conta.tipo} onChange={e=>setConta({...conta,tipo:e.target.value as ContaFinanceira["tipo"]})} className={campo}><option>Caixa</option><option>Conta corrente</option><option>Poupança</option><option>Investimento</option></select></FormField><div className="grid gap-3 sm:grid-cols-2"><FormField id="conta-banco" label="Banco" optional><input id="conta-banco" value={conta.banco} onChange={e=>setConta({...conta,banco:e.target.value})} className={campo}/></FormField><FormField id="conta-agencia" label="Agência" optional><input id="conta-agencia" value={conta.agencia} onChange={e=>setConta({...conta,agencia:e.target.value})} className={campo}/></FormField></div><FormField id="conta-numero" label="Número da conta" optional><input id="conta-numero" value={conta.numero} onChange={e=>setConta({...conta,numero:e.target.value})} className={campo}/></FormField><FormField id="conta-saldo" label="Saldo inicial"><input id="conta-saldo" type="number" step="0.01" value={conta.saldoInicial} onChange={e=>setConta({...conta,saldoInicial:Number(e.target.value)})} className={campo}/></FormField><button disabled={salvando} className="w-full rounded-xl bg-amber-400 px-5 py-3 font-bold text-black">{salvando?"Salvando…":"Salvar conta"}</button></div></form><div className="space-y-3">{dados.contas.map(i=><article key={i.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="font-bold">{i.nome}</h3><StatusBadge status={i.ativa?"Ativa":"Inativa"}/></div><p className="mt-1 text-sm text-zinc-400">{i.tipo}{i.banco?` · ${i.banco}`:""}</p></div><div className="flex gap-2"><button onClick={()=>setConta(i)} className="rounded-xl border border-sky-400/25 px-3 py-2 text-sm text-sky-200">Editar</button><button onClick={()=>setExclusao({tabela:"contas_financeiras",id:i.id,nome:i.nome})} className="rounded-xl border border-red-400/25 px-3 py-2 text-sm text-red-200">Remover</button></div></article>)}{!dados.contas.length&&!erro&&<EmptyState title="Nenhuma conta cadastrada" description="Cadastre o caixa e as contas bancárias utilizadas pela Loja."/>}</div></div>}
 {aba==="Categorias"&&<div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={salvarCategoria} className="rounded-2xl border border-white/10 bg-black/15 p-5"><h2 className="text-xl font-bold">{categoria.id?"Editar categoria":"Nova categoria"}</h2><div className="mt-5 space-y-4"><FormField id="categoria-nome" label="Nome" required><input id="categoria-nome" value={categoria.nome} onChange={e=>setCategoria({...categoria,nome:e.target.value})} className={campo}/></FormField><FormField id="categoria-natureza" label="Natureza"><select id="categoria-natureza" value={categoria.natureza} onChange={e=>setCategoria({...categoria,natureza:e.target.value as CategoriaFinanceira["natureza"]})} className={campo}><option>Receita</option><option>Despesa</option></select></FormField><FormField id="categoria-cor" label="Cor"><input id="categoria-cor" type="color" value={categoria.cor} onChange={e=>setCategoria({...categoria,cor:e.target.value})} className={`${campo} h-12`}/></FormField><button disabled={salvando} className="w-full rounded-xl bg-amber-400 px-5 py-3 font-bold text-black">Salvar categoria</button></div></form><div className="space-y-3">{dados.categorias.map(i=><article key={i.id} className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 p-4"><div className="flex items-center gap-3"><span className="h-4 w-4 rounded-full" style={{background:i.cor}}/><div><h3 className="font-bold">{i.nome}</h3><p className="text-xs text-zinc-500">{i.natureza}</p></div></div><div className="flex gap-2"><button onClick={()=>setCategoria(i)} className="rounded-xl border border-sky-400/25 px-3 py-2 text-sm text-sky-200">Editar</button><button onClick={()=>setExclusao({tabela:"categorias_financeiras",id:i.id,nome:i.nome})} className="rounded-xl border border-red-400/25 px-3 py-2 text-sm text-red-200">Remover</button></div></article>)}</div></div>}
 {aba==="Centros de custo"&&<div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={salvarCentro} className="rounded-2xl border border-white/10 bg-black/15 p-5"><h2 className="text-xl font-bold">{centro.id?"Editar centro":"Novo centro de custo"}</h2><div className="mt-5 space-y-4"><FormField id="centro-nome" label="Nome" required><input id="centro-nome" value={centro.nome} onChange={e=>setCentro({...centro,nome:e.target.value})} placeholder="Ex.: Manutenção do Templo" className={campo}/></FormField><FormField id="centro-descricao" label="Descrição" optional><textarea id="centro-descricao" value={centro.descricao} onChange={e=>setCentro({...centro,descricao:e.target.value})} className={campo}/></FormField><button disabled={salvando} className="w-full rounded-xl bg-amber-400 px-5 py-3 font-bold text-black">Salvar centro</button></div></form><div className="space-y-3">{dados.centros.map(i=><article key={i.id} className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 p-4"><div><h3 className="font-bold">{i.nome}</h3><p className="mt-1 text-sm text-zinc-500">{i.descricao||"Sem descrição"}</p></div><div className="flex gap-2"><button onClick={()=>setCentro(i)} className="rounded-xl border border-sky-400/25 px-3 py-2 text-sm text-sky-200">Editar</button><button onClick={()=>setExclusao({tabela:"centros_custo",id:i.id,nome:i.nome})} className="rounded-xl border border-red-400/25 px-3 py-2 text-sm text-red-200">Remover</button></div></article>)}{!dados.centros.length&&!erro&&<EmptyState title="Nenhum centro de custo" description="Crie centros para analisar onde os recursos da Loja são utilizados."/>}</div></div>}
 </section>{exclusao&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4"><section role="alertdialog" aria-modal="true" className="w-full max-w-md rounded-3xl border border-red-400/25 bg-[#111312] p-6"><h2 className="text-2xl font-bold">Remover cadastro?</h2><p className="mt-2 text-sm text-zinc-400">“{exclusao.nome}” será removido. Lançamentos vinculados impedirão a exclusão para preservar o histórico.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setExclusao(null)} className="rounded-xl border border-white/10 px-5 py-3">Cancelar</button><button onClick={()=>void remover()} className="rounded-xl bg-red-500 px-5 py-3 font-bold">Remover</button></div></section></div>}</div>;
}
