"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { listarFechamentosMensais, listarGestoes, type FechamentoMensal, type GestaoOperacional } from "@/lib/supabase/operacional";
const moeda=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const mesBR=(m:string)=>new Date(`${m.slice(0,7)}-02T12:00:00`).toLocaleDateString("pt-BR",{month:"short",year:"numeric"});
export function FechamentosResumoClient({completo=false}:{completo?:boolean}){
 const [gestoes,setGestoes]=useState<GestaoOperacional[]>([]),[itens,setItens]=useState<FechamentoMensal[]>([]),[erro,setErro]=useState("");
 useEffect(()=>{Promise.all([listarGestoes(),listarFechamentosMensais()]).then(([g,f])=>{setGestoes(g);setItens(f);}).catch(()=>setErro("Fechamentos mensais indisponíveis até a aplicação da migration."));},[]);
 const gestao=gestoes.find(g=>g.status==="Atual"||g.ativa);const daGestao=useMemo(()=>itens.filter(i=>i.gestaoId===gestao?.id),[itens,gestao]);const atual=daGestao.find(i=>i.competencia.startsWith(new Date().toISOString().slice(0,7)));const ultimo=daGestao.filter(i=>i.status==="Aprovado").sort((a,b)=>b.competencia.localeCompare(a.competencia))[0];
 if(erro)return null;
 return <section className="mt-6 sigma-surface rounded-3xl p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Prestação mensal</p><h2 className="mt-2 text-xl font-black">Fechamentos da gestão</h2><p className="mt-1 text-sm text-zinc-400">{atual?`Mês atual: ${atual.status}`:"O mês atual ainda não foi fechado."}</p></div><Link href="/tesouraria/fechamento-mensal" className="rounded-xl bg-amber-400 px-4 py-3 text-center font-bold text-black">Abrir fechamento mensal</Link></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-white/10 p-4"><p className="text-sm text-zinc-400">Status do mês</p><div className="mt-2"><StatusBadge status={atual?.status??"Aberto"}/></div></article><article className="rounded-2xl border border-white/10 p-4"><p className="text-sm text-zinc-400">Último aprovado</p><p className="mt-2 font-bold capitalize">{ultimo?mesBR(ultimo.competencia):"Nenhum"}</p></article><article className="rounded-2xl border border-white/10 p-4"><p className="text-sm text-zinc-400">Saldo aprovado</p><p className="mt-2 font-black text-emerald-300">{moeda(ultimo?.saldoFinal??0)}</p></article></div>
 {completo&&<div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left text-zinc-400"><tr><th className="p-3">Mês</th><th className="p-3">Status</th><th className="p-3 text-right">Entradas</th><th className="p-3 text-right">Saídas</th><th className="p-3 text-right">Saldo final</th><th className="p-3">Aprovado em</th></tr></thead><tbody>{daGestao.map(i=><tr key={i.id} className="border-t border-white/10"><td className="p-3 capitalize">{mesBR(i.competencia)}</td><td className="p-3"><StatusBadge status={i.status}/></td><td className="p-3 text-right">{moeda(i.totalEntradas)}</td><td className="p-3 text-right">{moeda(i.totalSaidas)}</td><td className="p-3 text-right font-bold">{moeda(i.saldoFinal)}</td><td className="p-3">{i.aprovadoEm?new Date(i.aprovadoEm).toLocaleDateString("pt-BR"):"—"}</td></tr>)}</tbody></table></div>}</section>;
}
