"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { EmptyState, Feedback, LoadingState } from "@/components/ui/Feedback";
import { FormField } from "@/components/ui/FormField";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { abrirRelatorio } from "@/lib/relatorios/client";
import { carregarCadastrosFinanceiros, carregarTesouraria, listarFechamentosMensais, listarGestoes, listarLivroCaixa, listarObreiros, salvarFechamentoMensal, type CadastrosFinanceiros, type FechamentoMensal, type GestaoOperacional, type LancamentoLivroCaixa, type StatusFechamentoMensal, type TesourariaBanco } from "@/lib/supabase/operacional";

const campo="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none focus:border-amber-300/60";
const moeda=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const oficiais=["Lançado","Conferido","Aprovado","Conciliado"];
const mesAtual=()=>new Date().toISOString().slice(0,7);
const mesBR=(m:string)=>new Date(`${m}-02T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});
type Parcela={vencimento:string;valor:number;pago:boolean};
type Resumo={saldoInicial:number;entradas:number;saidas:number;saldoFinal:number;mensalidadesRecebidas:number;mensalidadesAbertas:number;tronco:number;despesasPagas:number;despesasPendentes:number;semComprovante:number;rascunhos:number;cancelados:number};

export function FechamentoMensalClient(){
 const [gestoes,setGestoes]=useState<GestaoOperacional[]>([]),[lancamentos,setLancamentos]=useState<LancamentoLivroCaixa[]>([]),[fechamentos,setFechamentos]=useState<FechamentoMensal[]>([]);
 const [tesouraria,setTesouraria]=useState<TesourariaBanco>({regras:[],recebimentos:[],lancamentos:[],custos:[]}); const [cadastros,setCadastros]=useState<CadastrosFinanceiros>({contas:[],categorias:[],centros:[]}); const [ativos,setAtivos]=useState(0);
 const [competencia,setCompetencia]=useState(mesAtual()); const [obs,setObs]=useState(""),[obsAprovacao,setObsAprovacao]=useState(""),[motivo,setMotivo]=useState(""); const [carregando,setCarregando]=useState(true),[salvando,setSalvando]=useState(false),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState(""); const [confirmacao,setConfirmacao]=useState<StatusFechamentoMensal|null>(null);
 const gestao=useMemo(()=>gestoes.find(g=>g.status==="Atual"||g.ativa),[gestoes]);
 useEffect(()=>{Promise.all([listarGestoes(),listarLivroCaixa(),listarFechamentosMensais(),carregarTesouraria(),carregarCadastrosFinanceiros(),listarObreiros()]).then(([g,l,f,t,c,o])=>{setGestoes(g);setLancamentos(l);setFechamentos(f);setTesouraria(t);setCadastros(c);setAtivos(o.filter(i=>i.situacao==="Ativo").length);const atual=g.find(i=>i.status==="Atual"||i.ativa);if(atual){const agora=mesAtual();const inicio=atual.dataInicioGestao.slice(0,7),fim=atual.dataFimGestao.slice(0,7);setCompetencia(agora<inicio?inicio:agora>fim?fim:agora);}}).catch((e:unknown)=>setErro(e instanceof Error?e.message:"Não foi possível carregar o fechamento mensal.")).finally(()=>setCarregando(false));},[]);
 const fechamento=useMemo(()=>fechamentos.find(f=>f.gestaoId===gestao?.id&&f.competencia.startsWith(competencia)),[fechamentos,gestao,competencia]);
 useEffect(()=>{setObs(fechamento?.observacoesTesoureiro??"");setObsAprovacao(fechamento?.observacoesAprovacao??"");setMotivo("");},[fechamento]);
 const doMes=useMemo(()=>lancamentos.filter(l=>l.gestaoId===gestao?.id&&l.data.startsWith(competencia)),[lancamentos,gestao,competencia]);
 const validos=useMemo(()=>doMes.filter(l=>oficiais.includes(l.status)),[doMes]);
 const anterior=useMemo(()=>fechamentos.filter(f=>f.gestaoId===gestao?.id&&f.competencia.slice(0,7)<competencia&&f.status==="Aprovado").sort((a,b)=>b.competencia.localeCompare(a.competencia))[0],[fechamentos,gestao,competencia]);
 const resumo=useMemo<Resumo>(()=>{const saldoGestao=gestao?(gestao.financeiroPositivoRecebido-gestao.financeiroNegativoRecebido):0;const anteriores=lancamentos.filter(l=>l.gestaoId===gestao?.id&&l.data.slice(0,7)<competencia&&oficiais.includes(l.status)).reduce((s,l)=>s+(l.natureza==="Entrada"?l.valor:-l.valor),0);const primeiro=gestao?.dataInicioGestao.slice(0,7)===competencia;const saldoInicial=anterior?.saldoFinal??(primeiro?saldoGestao:saldoGestao+anteriores);const entradas=validos.filter(l=>l.natureza==="Entrada").reduce((s,l)=>s+l.valor,0),saidas=validos.filter(l=>l.natureza==="Saída").reduce((s,l)=>s+l.valor,0);const mensalidadesRecebidas=tesouraria.recebimentos.filter(r=>r.mesLancamento===competencia).reduce((s,r)=>s+r.valor,0);const regra=[...tesouraria.regras].filter(r=>r.dataInicio.slice(0,7)<=competencia).sort((a,b)=>b.dataInicio.localeCompare(a.dataInicio))[0];const mensalidadesAbertas=Math.max(0,(regra?.valor??0)*ativos-mensalidadesRecebidas);const parcelas=tesouraria.custos.flatMap(c=>(c.parcelas as Parcela[])).filter(p=>p.vencimento?.startsWith(competencia));return{saldoInicial,entradas,saidas,saldoFinal:saldoInicial+entradas-saidas,mensalidadesRecebidas,mensalidadesAbertas,tronco:validos.filter(l=>l.origem==="Tronco").reduce((s,l)=>s+l.valor,0),despesasPagas:saidas,despesasPendentes:parcelas.filter(p=>!p.pago).reduce((s,p)=>s+Number(p.valor||0),0),semComprovante:validos.filter(l=>l.natureza==="Saída"&&!l.comprovanteUrl&&!l.comprovanteObservacao).length,rascunhos:doMes.filter(l=>l.status==="Rascunho").length,cancelados:doMes.filter(l=>l.status==="Cancelado").length};},[gestao,lancamentos,competencia,anterior,validos,tesouraria,ativos,doMes]);
 const grupos=(natureza:"Entrada"|"Saída")=>{const mapa=new Map<string,{nome:string,total:number,qtd:number}>();validos.filter(l=>l.natureza===natureza).forEach(l=>{const nome=cadastros.categorias.find(c=>c.id===l.categoriaId)?.nome??"Sem categoria";const atual=mapa.get(nome)??{nome,total:0,qtd:0};atual.total+=l.valor;atual.qtd++;mapa.set(nome,atual);});return [...mapa.values()].sort((a,b)=>b.total-a.total);};
 const receitas=grupos("Entrada"),despesas=grupos("Saída"); const foraPeriodo=!!gestao&&(competencia<gestao.dataInicioGestao.slice(0,7)||competencia>gestao.dataFimGestao.slice(0,7)); const protegido=["Fechado","Aprovado"].includes(fechamento?.status??"");
 function objeto(status:StatusFechamentoMensal):FechamentoMensal{return{id:fechamento?.id??"",gestaoId:gestao?.id??"",competencia:`${competencia}-01`,status,saldoInicial:resumo.saldoInicial,totalEntradas:resumo.entradas,totalSaidas:resumo.saidas,saldoFinal:resumo.saldoFinal,mensalidadesRecebidas:resumo.mensalidadesRecebidas,mensalidadesAbertas:resumo.mensalidadesAbertas,totalTronco:resumo.tronco,despesasPagas:resumo.despesasPagas,despesasPendentes:resumo.despesasPendentes,semComprovante:resumo.semComprovante,observacoesTesoureiro:obs,observacoesAprovacao:obsAprovacao,motivoReabertura:motivo,responsavelFechamentoId:fechamento?.responsavelFechamentoId??"",responsavelAprovacaoId:fechamento?.responsavelAprovacaoId??"",fechadoEm:fechamento?.fechadoEm??"",aprovadoEm:fechamento?.aprovadoEm??"",criadoEm:fechamento?.criadoEm??"",atualizadoEm:fechamento?.atualizadoEm??""};}
 async function persistir(status:StatusFechamentoMensal){if(!gestao)return setErro("Cadastre uma gestão atual para realizar fechamentos mensais.");if(foraPeriodo)return setErro("O mês selecionado está fora do período da gestão.");if(status==="Fechado"&&!obs.trim())return setErro("Informe a observação do fechamento.");if(status==="Aprovado"&&fechamento?.status!=="Fechado")return setErro("Feche o mês antes de aprová-lo.");if(status==="Reaberto"&&!motivo.trim())return setErro("Informe o motivo administrativo da reabertura.");setSalvando(true);setErro("");try{const salvo=await salvarFechamentoMensal(objeto(status));setFechamentos(v=>fechamento?v.map(i=>i.id===salvo.id?salvo:i):[salvo,...v]);setSucesso(status==="Aprovado"?"Fechamento aprovado oficialmente.":status==="Reaberto"?"Período reaberto com justificativa.":"Fechamento mensal salvo.");setConfirmacao(null);}catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar o fechamento.");}finally{setSalvando(false);}}
 function pdf(){abrirRelatorio("fechamento-mensal",{inicio:`${competencia}-01`,fim:`${competencia}-31`});}
 if(carregando)return <div className="mt-8"><LoadingState label="Consolidando fechamento mensal…"/></div>;
 if(!gestao)return <div className="mt-8"><Feedback tone="warning">Cadastre uma gestão atual para realizar fechamentos mensais. <Link href="/configuracoes" className="font-bold underline">Abrir Gestão</Link></Feedback></div>;
 return <div className="mt-8 space-y-6">{erro&&<Feedback tone="error">{erro.includes("fechamentos_mensais")?"A migration 20260720_monthly_closing.sql precisa ser aplicada no Supabase.":erro}</Feedback>}{sucesso&&<Feedback tone="success">{sucesso}</Feedback>}
 <section className="sigma-surface rounded-3xl p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Fechamento Mensal</p><h2 className="mt-2 text-2xl font-black">{gestao.nomeGestao}</h2><p className="text-sm text-zinc-400">{gestao.dataInicioGestao.split("-").reverse().join("/")} a {gestao.dataFimGestao.split("-").reverse().join("/")}</p></div><div className="flex flex-wrap items-end gap-3"><FormField id="fm-competencia" label="Mês de referência"><input id="fm-competencia" type="month" value={competencia} min={gestao.dataInicioGestao.slice(0,7)} max={gestao.dataFimGestao.slice(0,7)} onChange={e=>setCompetencia(e.target.value)} className={campo}/></FormField><button onClick={()=>void pdf()} className="rounded-xl border border-white/10 px-4 py-3 font-bold">Exportar PDF</button><StatusBadge status={fechamento?.status??"Aberto"}/></div></div>{protegido&&<div className="mt-5"><Feedback tone="warning">Este período possui fechamento mensal protegido. Reabra-o com justificativa antes de alterar o Livro Caixa.</Feedback></div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Saldo inicial",resumo.saldoInicial,"amber"],["Entradas",resumo.entradas,"emerald"],["Saídas",resumo.saidas,"red"],["Saldo final",resumo.saldoFinal,"sky"]].map(([t,v,c])=><article key={String(t)} className="rounded-2xl border border-white/10 bg-black/20 p-5"><p className="text-sm text-zinc-400">{t}</p><p className={`mt-2 text-2xl font-black text-${c}-300`}>{moeda(Number(v))}</p></article>)}</div></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Mensalidades recebidas",moeda(resumo.mensalidadesRecebidas)],["Mensalidades em aberto",moeda(resumo.mensalidadesAbertas)],["Tronco de Solidariedade",moeda(resumo.tronco)],["Despesas pendentes",moeda(resumo.despesasPendentes)]].map(([t,v])=><article key={t} className="sigma-surface rounded-2xl p-5"><p className="text-sm text-zinc-400">{t}</p><p className="mt-2 text-xl font-black text-amber-200">{v}</p></article>)}</section>
 <section className="grid gap-6 lg:grid-cols-2">{[["Receitas por categoria",receitas,resumo.entradas],["Despesas por categoria",despesas,resumo.saidas]].map(([titulo,itens,total])=><div key={String(titulo)} className="sigma-surface rounded-3xl p-5"><h2 className="text-xl font-black">{titulo as string}</h2><div className="mt-4 space-y-3">{(itens as typeof receitas).map(i=><div key={i.nome} className="rounded-2xl border border-white/10 p-4"><div className="flex justify-between gap-4"><div><p className="font-bold">{i.nome}</p><p className="text-xs text-zinc-500">{i.qtd} lançamento(s)</p></div><p className="font-black">{moeda(i.total)}</p></div><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-amber-400" style={{width:`${Number(total)>0?Math.min(100,i.total/Number(total)*100):0}%`}}/></div></div>)}{!(itens as typeof receitas).length&&<EmptyState title="Sem movimentações" description="Nenhum lançamento oficial desta natureza no período."/>}</div></div>)}</section>
 <section className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="sigma-surface rounded-3xl p-5"><h2 className="text-xl font-black">Pendências e alertas</h2><div className="mt-4 space-y-3">{!anterior&&gestao.dataInicioGestao.slice(0,7)<competencia&&<Feedback tone="warning">O mês anterior ainda não possui fechamento aprovado. O saldo foi calculado pelo Livro Caixa.</Feedback>}{resumo.semComprovante>0&&<Feedback tone="warning">Existem {resumo.semComprovante} saída(s) sem comprovante.</Feedback>}{resumo.mensalidadesAbertas>0&&<Feedback tone="warning">Há mensalidades em aberto no período.</Feedback>}{resumo.rascunhos>0&&<Feedback tone="warning">Existem {resumo.rascunhos} lançamento(s) em rascunho fora dos totais oficiais.</Feedback>}{resumo.cancelados>0&&<Feedback tone="info">{resumo.cancelados} lançamento(s) cancelado(s) no período.</Feedback>}{!resumo.semComprovante&&!resumo.mensalidadesAbertas&&!resumo.rascunhos&&<Feedback tone="success">Nenhuma pendência financeira crítica identificada.</Feedback>}</div></div>
 <div className="sigma-surface rounded-3xl p-5"><h2 className="text-xl font-black">Conferência e aprovação</h2><div className="mt-4 space-y-4"><FormField id="fm-obs" label="Observações do tesoureiro" required><textarea id="fm-obs" value={obs} disabled={protegido} onChange={e=>setObs(e.target.value)} className={campo} rows={4}/></FormField><FormField id="fm-aprovacao" label="Observações da aprovação" optional><textarea id="fm-aprovacao" value={obsAprovacao} disabled={fechamento?.status==="Aprovado"} onChange={e=>setObsAprovacao(e.target.value)} className={campo}/></FormField>{protegido&&<FormField id="fm-motivo" label="Motivo da reabertura" required><textarea id="fm-motivo" value={motivo} onChange={e=>setMotivo(e.target.value)} className={campo}/></FormField>}<div className="flex flex-wrap justify-end gap-2">{!protegido&&<><button disabled={salvando} onClick={()=>void persistir("Aberto")} className="rounded-xl border border-white/10 px-4 py-3">Salvar conferência</button><button disabled={salvando} onClick={()=>void persistir("Em conferência")} className="rounded-xl border border-sky-400/30 px-4 py-3 text-sky-200">Em conferência</button><button disabled={salvando} onClick={()=>setConfirmacao("Fechado")} className="rounded-xl bg-amber-400 px-4 py-3 font-bold text-black">Fechar mês</button></>}{fechamento?.status==="Fechado"&&<button disabled={salvando} onClick={()=>setConfirmacao("Aprovado")} className="rounded-xl bg-emerald-500 px-4 py-3 font-bold text-black">Aprovar</button>}{protegido&&<button disabled={salvando} onClick={()=>setConfirmacao("Reaberto")} className="rounded-xl bg-red-500 px-4 py-3 font-bold">Reabrir com justificativa</button>}</div></div></div></section>
 <section className="sigma-surface rounded-3xl p-5"><h2 className="text-xl font-black">Histórico da gestão</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left text-zinc-400"><tr><th className="p-3">Competência</th><th className="p-3">Status</th><th className="p-3 text-right">Entradas</th><th className="p-3 text-right">Saídas</th><th className="p-3 text-right">Saldo final</th><th className="p-3">Aprovação</th></tr></thead><tbody>{fechamentos.filter(f=>f.gestaoId===gestao.id).map(f=><tr key={f.id} className="border-t border-white/10"><td className="p-3 capitalize">{mesBR(f.competencia.slice(0,7))}</td><td className="p-3"><StatusBadge status={f.status}/></td><td className="p-3 text-right">{moeda(f.totalEntradas)}</td><td className="p-3 text-right">{moeda(f.totalSaidas)}</td><td className="p-3 text-right font-bold">{moeda(f.saldoFinal)}</td><td className="p-3">{f.aprovadoEm?new Date(f.aprovadoEm).toLocaleString("pt-BR"):"—"}</td></tr>)}</tbody></table></div></section>
 {confirmacao&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-4"><section role="alertdialog" aria-modal="true" className="w-full max-w-lg rounded-3xl border border-amber-400/25 bg-[#111312] p-6"><h2 className="text-2xl font-black">Confirmar {confirmacao.toLowerCase()}?</h2><p className="mt-3 text-sm leading-6 text-zinc-300">{confirmacao==="Fechado"?"Após fechar o mês, os dados serão preservados para prestação de contas. Confira receitas, despesas, mensalidades, tronco e comprovantes.":confirmacao==="Aprovado"?"A aprovação confirma oficialmente a prestação mensal. Alterações futuras deverão ser justificadas.":"A reabertura libera o período para correções e ficará registrada na auditoria."}</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setConfirmacao(null)} className="rounded-xl border border-white/10 px-5 py-3">Cancelar</button><button onClick={()=>void persistir(confirmacao)} className="rounded-xl bg-amber-400 px-5 py-3 font-black text-black">Confirmar</button></div></section></div>}
 </div>;
}
