"use client";

import { type FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { EmptyState, Feedback, LoadingState } from "@/components/ui/Feedback";
import { FormField } from "@/components/ui/FormField";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { saldoInicialLiquido } from "@/lib/financeiro";
import {
  carregarCadastrosFinanceiros, excluirLancamentoLivroCaixa, listarGestoes, listarLivroCaixa,
  salvarLancamentoLivroCaixa, type CadastrosFinanceiros, type GestaoOperacional,
  type LancamentoLivroCaixa, type StatusLivroCaixa,
} from "@/lib/supabase/operacional";

const campo = "w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none focus:border-amber-300/60";
const hoje = () => new Date().toISOString().slice(0, 10);
const competenciaAtual = () => hoje().slice(0, 7);
const moeda = (valor: number) => valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dataBR = (data: string) => data ? data.split("-").reverse().join("/") : "—";
const oficiais: StatusLivroCaixa[] = ["Lançado", "Conferido", "Aprovado", "Conciliado"];
const statusDisponiveis: StatusLivroCaixa[] = ["Rascunho", ...oficiais, "Cancelado"];

function vazio(gestaoId = ""): LancamentoLivroCaixa {
  return { id:"", gestaoId, data:hoje(), competencia:`${competenciaAtual()}-01`, natureza:"Entrada", origem:"Manual", contaId:"", categoriaId:"", centroCustoId:"", formaPagamento:"PIX", valor:0, descricao:"", observacoes:"", status:"Lançado", comprovanteUrl:"", comprovanteObservacao:"", documentoNumero:"", comprovanteData:"", responsavelId:"", criadoEm:"", atualizadoEm:"" };
}

export function LivroCaixaClient() {
  const [lancamentos, setLancamentos] = useState<LancamentoLivroCaixa[]>([]);
  const [cadastros, setCadastros] = useState<CadastrosFinanceiros>({contas:[],categorias:[],centros:[]});
  const [gestoes, setGestoes] = useState<GestaoOperacional[]>([]);
  const [form, setForm] = useState<LancamentoLivroCaixa>(vazio());
  const [mes, setMes] = useState(competenciaAtual());
  const [tipo, setTipo] = useState(""); const [categoria, setCategoria] = useState("");
  const [conta, setConta] = useState(""); const [centro, setCentro] = useState(""); const [status, setStatus] = useState("");
  const [carregando, setCarregando] = useState(true); const [salvando, setSalvando] = useState(false);
  const [erro, setErro] = useState(""); const [sucesso, setSucesso] = useState("");
  const [remover, setRemover] = useState<LancamentoLivroCaixa|null>(null);

  const gestaoAtual = useMemo(() => gestoes.find(g => g.status === "Atual" || g.ativa), [gestoes]);
  useEffect(() => { Promise.all([listarLivroCaixa(), carregarCadastrosFinanceiros(), listarGestoes()]).then(([l,c,g]) => { setLancamentos(l); setCadastros(c); setGestoes(g); const atual=g.find(i=>i.status==="Atual"||i.ativa); setForm(vazio(atual?.id)); }).catch((e:unknown)=>setErro(e instanceof Error?e.message:"Não foi possível carregar o Livro Caixa.")).finally(()=>setCarregando(false)); }, []);

  const categoriasDoTipo = useMemo(() => cadastros.categorias.filter(c => c.ativa && (c.natureza === "Ambos" || c.natureza === (form.natureza === "Entrada" ? "Receita" : "Despesa"))), [cadastros.categorias, form.natureza]);
  const filtrados = useMemo(() => lancamentos.filter(l => (!mes || l.data.startsWith(mes)) && (!tipo || l.natureza===tipo) && (!categoria || l.categoriaId===categoria) && (!conta || l.contaId===conta) && (!centro || l.centroCustoId===centro) && (!status || l.status===status)), [lancamentos,mes,tipo,categoria,conta,centro,status]);
  const oficiaisGestao = useMemo(() => lancamentos.filter(l => oficiais.includes(l.status) && (!gestaoAtual || l.gestaoId === gestaoAtual.id)), [lancamentos,gestaoAtual]);
  const saldoInicial = gestaoAtual ? saldoInicialLiquido(gestaoAtual.financeiroPositivoRecebido, gestaoAtual.financeiroNegativoRecebido) : 0;
  const entradasMes = oficiaisGestao.filter(l=>l.natureza==="Entrada"&&l.data.startsWith(mes)).reduce((s,l)=>s+l.valor,0);
  const saidasMes = oficiaisGestao.filter(l=>l.natureza==="Saída"&&l.data.startsWith(mes)).reduce((s,l)=>s+l.valor,0);
  const movimentoTotal = oficiaisGestao.reduce((s,l)=>s+(l.natureza==="Entrada"?l.valor:-l.valor),0);
  const semComprovante = oficiaisGestao.filter(l=>l.natureza==="Saída"&&!l.comprovanteUrl&&!l.comprovanteObservacao).length;
  const pendentes = lancamentos.filter(l=>["Rascunho","Conferido"].includes(l.status)).length;
  const saldos = cadastros.contas.filter(c=>c.ativa).map(c=>({ ...c, saldo:c.saldoInicial+oficiaisGestao.filter(l=>l.contaId===c.id).reduce((s,l)=>s+(l.natureza==="Entrada"?l.valor:-l.valor),0) }));

  function validar() { if(!gestaoAtual)return "Cadastre uma gestão atual para organizar corretamente os lançamentos financeiros."; if(!form.data)return "Informe a data do lançamento."; if(!(form.valor>0))return "Informe um valor maior que zero."; if(!form.contaId)return "Selecione a conta financeira."; if(!form.categoriaId)return "Selecione a categoria financeira."; if(form.origem==="Manual"&&!form.descricao.trim())return "Informe a descrição do lançamento manual."; return ""; }
  async function salvar(e:FormEvent) { e.preventDefault(); const falha=validar(); if(falha){setErro(falha);return;} setSalvando(true);setErro("");setSucesso("");try{const salvo=await salvarLancamentoLivroCaixa({...form,gestaoId:gestaoAtual?.id??""});setLancamentos(v=>form.id?v.map(i=>i.id===form.id?salvo:i):[salvo,...v]);setForm(vazio(gestaoAtual?.id));setSucesso("Lançamento salvo com sucesso.");}catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar o lançamento.");}finally{setSalvando(false);} }
  async function excluir() { if(!remover)return; try{await excluirLancamentoLivroCaixa(remover.id);setLancamentos(v=>v.filter(i=>i.id!==remover.id));setSucesso("Lançamento excluído e registrado na auditoria.");setRemover(null);}catch(e){setErro(e instanceof Error?e.message:"Não foi possível excluir.");} }
  function editar(item:LancamentoLivroCaixa){setForm(item);globalThis.scrollTo?.({top:0,behavior:"smooth"});}

  if(carregando)return <div className="mt-8"><LoadingState label="Carregando Livro Caixa…"/></div>;
  return <div className="mt-8 space-y-6">
    {!gestaoAtual&&<Feedback tone="warning">Cadastre uma gestão atual para organizar corretamente os lançamentos financeiros. <Link className="font-bold underline" href="/configuracoes">Abrir Gestão</Link></Feedback>}
    {erro&&<Feedback tone="error">{erro.includes("status_caixa")||erro.includes("natureza")?"A migration 20260719_cash_ledger.sql precisa ser aplicada no Supabase antes de usar o Livro Caixa.":erro}</Feedback>}{sucesso&&<Feedback tone="success">{sucesso}</Feedback>}
    <section className="sigma-surface rounded-3xl p-5 sm:p-7"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Gestão financeira</p><h2 className="mt-2 text-2xl font-black">{gestaoAtual?.nomeGestao??"Nenhuma gestão atual"}</h2><p className="mt-1 text-sm text-zinc-400">Movimentações oficiais, comprovantes e conciliação em um único lugar.</p></div><Link href="/tesouraria/configuracoes" className="rounded-xl border border-amber-300/30 px-4 py-3 text-sm font-bold text-amber-200">Configurar contas e categorias</Link></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Saldo inicial",saldoInicial],["Entradas no mês",entradasMes],["Saídas no mês",saidasMes],["Saldo estimado",saldoInicial+movimentoTotal]].map(([t,v])=><article key={String(t)} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-sm text-zinc-400">{t}</p><p className="mt-2 text-xl font-black text-amber-200">{moeda(Number(v))}</p></article>)}<article className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-sm text-zinc-400">Pendências</p><p className="mt-2 text-xl font-black text-amber-200">{pendentes}</p><p className="text-xs text-zinc-500">{semComprovante} saída(s) sem comprovante</p></article></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{saldos.map(c=><article key={c.id} className="sigma-surface rounded-2xl p-5"><div className="flex justify-between gap-2"><p className="font-bold">{c.nome}</p><StatusBadge status={c.ativa?"Ativa":"Inativa"}/></div><p className="mt-3 text-2xl font-black text-emerald-300">{moeda(c.saldo)}</p><p className="mt-1 text-xs text-zinc-500">{c.tipo} · saldo da conta</p></article>)}{!saldos.length&&<div className="sm:col-span-2 xl:col-span-4"><EmptyState title="Nenhuma conta financeira ativa" description="Cadastre ao menos uma conta para registrar entradas e saídas." action={<Link href="/tesouraria/configuracoes" className="rounded-xl bg-amber-400 px-4 py-3 font-bold text-black">Cadastrar conta</Link>}/></div>}</section>
    <section className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]">
      <form onSubmit={salvar} className="sigma-surface rounded-3xl p-5 sm:p-6"><h2 className="text-xl font-black">{form.id?"Editar lançamento":"Novo lançamento"}</h2><p className="mt-1 text-sm text-zinc-400">Campos marcados são obrigatórios.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">
        <FormField id="lc-natureza" label="Tipo" required><select id="lc-natureza" value={form.natureza} onChange={e=>setForm({...form,natureza:e.target.value as LancamentoLivroCaixa["natureza"],categoriaId:""})} className={campo}><option>Entrada</option><option>Saída</option></select></FormField>
        <FormField id="lc-origem" label="Origem" required><select id="lc-origem" value={form.origem} onChange={e=>setForm({...form,origem:e.target.value as LancamentoLivroCaixa["origem"]})} className={campo}>{["Manual","Mensalidade","Tronco","Despesa","Evento","Repasse","Outro"].map(i=><option key={i}>{i}</option>)}</select></FormField>
        <FormField id="lc-data" label="Data" required><input id="lc-data" type="date" value={form.data} onChange={e=>setForm({...form,data:e.target.value})} className={campo}/></FormField>
        <FormField id="lc-competencia" label="Competência" required><input id="lc-competencia" type="month" value={form.competencia.slice(0,7)} onChange={e=>setForm({...form,competencia:`${e.target.value}-01`})} className={campo}/></FormField>
        <FormField id="lc-valor" label="Valor" required><input id="lc-valor" type="number" min="0.01" step="0.01" value={form.valor||""} onChange={e=>setForm({...form,valor:Number(e.target.value)})} placeholder="0,00" className={campo}/></FormField>
        <FormField id="lc-conta" label="Conta" required><select id="lc-conta" value={form.contaId} onChange={e=>setForm({...form,contaId:e.target.value})} className={campo}><option value="">Selecione</option>{cadastros.contas.filter(i=>i.ativa).map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></FormField>
        <FormField id="lc-categoria" label="Categoria" required><select id="lc-categoria" value={form.categoriaId} onChange={e=>setForm({...form,categoriaId:e.target.value})} className={campo}><option value="">Selecione</option>{categoriasDoTipo.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></FormField>
        <FormField id="lc-centro" label="Centro de custo" optional><select id="lc-centro" value={form.centroCustoId} onChange={e=>setForm({...form,centroCustoId:e.target.value})} className={campo}><option value="">Selecione</option>{cadastros.centros.filter(i=>i.ativo).map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></FormField>
        <FormField id="lc-pagamento" label="Forma de pagamento"><select id="lc-pagamento" value={form.formaPagamento} onChange={e=>setForm({...form,formaPagamento:e.target.value})} className={campo}>{["Dinheiro","PIX","Transferência","Cartão","Boleto","Débito automático","Outro"].map(i=><option key={i}>{i}</option>)}</select></FormField>
        <FormField id="lc-status" label="Status" required><select id="lc-status" value={form.status} onChange={e=>setForm({...form,status:e.target.value as StatusLivroCaixa})} className={campo}>{statusDisponiveis.map(i=><option key={i}>{i}</option>)}</select></FormField>
        <FormField id="lc-descricao" label="Descrição" required={form.origem==="Manual"} className="sm:col-span-2"><input id="lc-descricao" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} placeholder="Descreva a movimentação" className={campo}/></FormField>
        <FormField id="lc-observacoes" label="Observações" optional className="sm:col-span-2"><textarea id="lc-observacoes" value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} className={campo}/></FormField>
        <FormField id="lc-comprovante" label="Link do comprovante" optional><input id="lc-comprovante" type="url" value={form.comprovanteUrl} onChange={e=>setForm({...form,comprovanteUrl:e.target.value})} placeholder="https://" className={campo}/></FormField>
        <FormField id="lc-documento" label="Número do documento" optional><input id="lc-documento" value={form.documentoNumero} onChange={e=>setForm({...form,documentoNumero:e.target.value})} className={campo}/></FormField>
        <FormField id="lc-comprovante-data" label="Data do comprovante" optional><input id="lc-comprovante-data" type="date" value={form.comprovanteData} onChange={e=>setForm({...form,comprovanteData:e.target.value})} className={campo}/></FormField>
        <FormField id="lc-comprovante-obs" label="Observação do comprovante" optional><input id="lc-comprovante-obs" value={form.comprovanteObservacao} onChange={e=>setForm({...form,comprovanteObservacao:e.target.value})} className={campo}/></FormField>
      </div>{["Rascunho","Cancelado"].includes(form.status)&&<p className="mt-4 text-sm text-amber-200">Este lançamento não compõe os totais oficiais.</p>}<div className="mt-6 flex flex-wrap justify-end gap-3">{form.id&&<button type="button" onClick={()=>setForm(vazio(gestaoAtual?.id))} className="rounded-xl border border-white/10 px-5 py-3">Cancelar edição</button>}<button disabled={salvando||!gestaoAtual} className="rounded-xl bg-amber-400 px-6 py-3 font-black text-black disabled:opacity-50">{salvando?"Salvando…":"Salvar lançamento"}</button></div></form>
      <div className="space-y-4"><div className="sigma-surface rounded-3xl p-5"><h2 className="text-xl font-black">Filtros do Livro Caixa</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input aria-label="Filtrar por mês" type="month" value={mes} onChange={e=>setMes(e.target.value)} className={campo}/><select aria-label="Filtrar por tipo" value={tipo} onChange={e=>setTipo(e.target.value)} className={campo}><option value="">Todos os tipos</option><option>Entrada</option><option>Saída</option></select><select aria-label="Filtrar por status" value={status} onChange={e=>setStatus(e.target.value)} className={campo}><option value="">Todos os status</option>{statusDisponiveis.map(i=><option key={i}>{i}</option>)}</select><select aria-label="Filtrar por conta" value={conta} onChange={e=>setConta(e.target.value)} className={campo}><option value="">Todas as contas</option>{cadastros.contas.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select><select aria-label="Filtrar por categoria" value={categoria} onChange={e=>setCategoria(e.target.value)} className={campo}><option value="">Todas as categorias</option>{cadastros.categorias.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select><select aria-label="Filtrar por centro de custo" value={centro} onChange={e=>setCentro(e.target.value)} className={campo}><option value="">Todos os centros</option>{cadastros.centros.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></div></div>
      <div className="sigma-surface overflow-hidden rounded-3xl"><div className="flex items-center justify-between p-5"><div><h2 className="text-xl font-black">Movimentações</h2><p className="text-sm text-zinc-400">{filtrados.length} resultado(s)</p></div></div>{!filtrados.length?<div className="p-5"><EmptyState title="Nenhum lançamento encontrado" description="Ajuste os filtros ou cadastre a primeira movimentação deste período."/></div>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-white/[.04] text-left text-zinc-400"><tr><th className="p-4">Data</th><th className="p-4">Descrição</th><th className="p-4">Conta / categoria</th><th className="p-4">Status</th><th className="p-4 text-right">Valor</th><th className="p-4 text-right">Ações</th></tr></thead><tbody>{filtrados.map(l=><tr key={l.id} className="border-t border-white/10"><td className="whitespace-nowrap p-4">{dataBR(l.data)}</td><td className="p-4"><p className="font-bold">{l.descricao||l.origem}</p><p className="text-xs text-zinc-500">{l.origem}{l.natureza==="Saída"&&!l.comprovanteUrl&&!l.comprovanteObservacao?" · sem comprovante":""}</p></td><td className="p-4 text-zinc-300">{cadastros.contas.find(i=>i.id===l.contaId)?.nome??"—"}<br/><span className="text-xs text-zinc-500">{cadastros.categorias.find(i=>i.id===l.categoriaId)?.nome??"—"}</span></td><td className="p-4"><StatusBadge status={l.status}/></td><td className={`p-4 text-right font-black ${l.natureza==="Entrada"?"text-emerald-300":"text-red-300"}`}>{l.natureza==="Entrada"?"+":"−"} {moeda(l.valor)}</td><td className="p-4 text-right whitespace-nowrap"><button onClick={()=>editar(l)} className="rounded-lg px-2 py-1 text-sky-200">Editar</button><button onClick={()=>setRemover(l)} className="rounded-lg px-2 py-1 text-red-200">Excluir</button></td></tr>)}</tbody></table></div>}</div></div>
    </section>
    {remover&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-4"><section role="alertdialog" aria-modal="true" className="w-full max-w-md rounded-3xl border border-red-400/25 bg-[#111312] p-6"><h2 className="text-2xl font-black">Excluir lançamento?</h2><p className="mt-2 text-sm text-zinc-400">{remover.descricao}. A exclusão ficará registrada na auditoria financeira.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setRemover(null)} className="rounded-xl border border-white/10 px-5 py-3">Voltar</button><button onClick={()=>void excluir()} className="rounded-xl bg-red-500 px-5 py-3 font-bold">Excluir</button></div></section></div>}
  </div>;
}
