"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { alterarStatusPreCadastro, converterPreCadastro, registrarVisualizacaoPreCadastro } from "@/app/pre-cadastros/actions";
import type { PreCadastroAdmin } from "@/lib/pre-cadastro-admin";
import { grausPreCadastro, statusPreCadastro, type StatusPreCadastro } from "@/lib/pre-cadastro-validacao";
import { EmptyState, Feedback } from "@/components/ui/Feedback";
import { StatusBadge } from "@/components/ui/StatusBadge";

const campo = "w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white";
type Duplicado = { id: string; nome: string; email: string | null; cim: string | null; cpf: string | null };

export function PreCadastrosAdminClient({ itens, podeCriarUsuario }: { itens: PreCadastroAdmin[]; podeCriarUsuario: boolean }) {
  const router = useRouter();
  const [status, setStatus] = useState(""); const [loja, setLoja] = useState(""); const [grau, setGrau] = useState("");
  const [data, setData] = useState(""); const [busca, setBusca] = useState(""); const [pareceres, setPareceres] = useState<Record<string, string>>({});
  const [processando, setProcessando] = useState(""); const [mensagem, setMensagem] = useState(""); const [erro, setErro] = useState(false);
  const [duplicados, setDuplicados] = useState<Record<string, Duplicado[]>>({}); const [visualizados, setVisualizados] = useState<string[]>([]);
  const lojas = useMemo(() => Array.from(new Map(itens.map((item) => [item.lojaId, { id: item.lojaId, nome: item.lojaNome }])).values()), [itens]);
  const filtrados = useMemo(() => itens.filter((item) => !status || item.status === status).filter((item) => !loja || item.lojaId === loja).filter((item) => !grau || item.grau === grau).filter((item) => !data || item.criadoEm.slice(0, 10) === data).filter((item) => !busca || `${item.nomeCompleto} ${item.email} ${item.telefone} ${item.cim} ${item.protocolo}`.toLocaleLowerCase("pt-BR").includes(busca.toLocaleLowerCase("pt-BR"))), [itens, status, loja, grau, data, busca]);
  const total = (alvo: string) => itens.filter((item) => item.status === alvo).length;

  async function movimentar(item: PreCadastroAdmin, novoStatus: StatusPreCadastro) {
    setProcessando(item.id); setMensagem(""); setErro(false);
    try { await alterarStatusPreCadastro({ id: item.id, status: novoStatus, parecer: pareceres[item.id] ?? item.parecer }); setMensagem(`Pré-cadastro ${novoStatus.toLocaleLowerCase("pt-BR")} com sucesso.`); router.refresh(); }
    catch (e) { setErro(true); setMensagem(e instanceof Error ? e.message : "Não foi possível atualizar."); }
    finally { setProcessando(""); }
  }
  async function converter(item: PreCadastroAdmin, obreiroExistenteId?: string) {
    setProcessando(item.id); setMensagem(""); setErro(false);
    try {
      const resultado = await converterPreCadastro({ id: item.id, obreiroExistenteId });
      if (!resultado.convertido) { setDuplicados((atual) => ({ ...atual, [item.id]: resultado.duplicados as Duplicado[] })); setMensagem("Possível duplicidade encontrada. Escolha o cadastro existente para vincular ou revise os dados."); }
      else { setDuplicados((atual) => ({ ...atual, [item.id]: [] })); setMensagem("Pré-cadastro convertido em Obreiro. A criação do usuário continua sendo uma ação separada."); router.refresh(); }
    } catch (e) { setErro(true); setMensagem(e instanceof Error ? e.message : "Não foi possível converter."); }
    finally { setProcessando(""); }
  }
  function visualizar(id: string, aberto: boolean) { if (!aberto || visualizados.includes(id)) return; setVisualizados((atual) => [...atual, id]); void registrarVisualizacaoPreCadastro(id); }

  return <div className="mt-8 space-y-6">
    {mensagem && <Feedback tone={erro ? "error" : duplicados && mensagem.includes("duplicidade") ? "warning" : "success"}>{mensagem}</Feedback>}
    <section className="grid grid-cols-2 gap-3 xl:grid-cols-5">{[["Pendentes", total("Pendente")], ["Em análise", total("Em análise")], ["Aprovados", total("Aprovado")], ["Recusados", total("Recusado")], ["Convertidos", total("Convertido em Obreiro")]].map(([titulo, valor]) => <article key={String(titulo)} className="sigma-surface rounded-2xl p-4"><p className="text-xs text-zinc-400 sm:text-sm">{titulo}</p><p className="mt-1 text-3xl font-black text-amber-200">{valor}</p></article>)}</section>
    <section className="sigma-surface grid gap-3 rounded-2xl p-4 md:grid-cols-3 xl:grid-cols-6"><label className="text-xs text-zinc-400">Palavra-chave, CIM ou e-mail<input type="search" value={busca} onChange={(e) => setBusca(e.target.value)} className={`mt-1 ${campo}`} /></label><label className="text-xs text-zinc-400">Loja<select value={loja} onChange={(e) => setLoja(e.target.value)} className={`mt-1 ${campo}`}><option value="">Todas</option>{lojas.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label className="text-xs text-zinc-400">Status<select value={status} onChange={(e) => setStatus(e.target.value)} className={`mt-1 ${campo}`}><option value="">Todos</option>{statusPreCadastro.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs text-zinc-400">Data<input type="date" value={data} onChange={(e) => setData(e.target.value)} className={`mt-1 ${campo}`} /></label><label className="text-xs text-zinc-400">Grau<select value={grau} onChange={(e) => setGrau(e.target.value)} className={`mt-1 ${campo}`}><option value="">Todos</option>{grausPreCadastro.map((item) => <option key={item}>{item}</option>)}</select></label><div className="flex items-end"><button type="button" onClick={() => { setBusca(""); setLoja(""); setStatus(""); setData(""); setGrau(""); }} className="min-h-11 w-full rounded-xl border border-white/10 px-4 py-2">Limpar filtros</button></div></section>
    <section className="space-y-3">{filtrados.length ? filtrados.map((item) => <details key={item.id} onToggle={(e) => visualizar(item.id, e.currentTarget.open)} className="group sigma-surface rounded-2xl p-4 sm:p-5"><summary className="flex cursor-pointer list-none flex-col gap-3 marker:content-none lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-amber-300">{item.protocolo} · {new Date(item.criadoEm).toLocaleString("pt-BR")}</p><h2 className="mt-1 break-words text-lg font-black">{item.nomeCompleto}</h2><p className="text-sm text-zinc-400">{item.lojaNumero ? `${item.lojaNome} nº ${item.lojaNumero}` : item.lojaNome} · CIM {item.cim} · {item.grau}</p></div><div className="flex items-center justify-between gap-3"><StatusBadge status={item.status} /><span className="rounded-xl border border-white/10 px-3 py-2 text-sm font-bold group-open:hidden">Ver detalhes</span><span className="hidden rounded-xl border border-white/10 px-3 py-2 text-sm font-bold group-open:inline">Recolher</span></div></summary>
      <div className="mt-4 border-t border-white/10 pt-4"><dl className="grid gap-2 text-sm sm:grid-cols-2 xl:grid-cols-4">{[["E-mail", item.email], ["Telefone", item.telefone], ["CPF", item.cpf || "Não informado"], ["Nascimento", item.dataNascimento ? new Date(`${item.dataNascimento}T12:00:00`).toLocaleDateString("pt-BR") : "Não informado"], ["Nome preferido", item.nomePreferido || "Não informado"], ["Situação informada", item.situacao], ["Loja de origem", item.lojaOrigem || "Não informada"], ["Oriente / Potência", [item.oriente, item.potencia].filter(Boolean).join(" · ") || "Não informado"], ["Cargo ou função", item.cargoFuncao || "Não informado"]].map(([rotulo, valor]) => <div key={rotulo} className="rounded-xl border border-white/10 p-3"><dt className="text-xs text-zinc-500">{rotulo}</dt><dd className="mt-1 break-words font-semibold">{valor}</dd></div>)}</dl>{item.observacoes && <p className="mt-3 rounded-xl bg-black/20 p-3 text-sm"><b>Observações:</b> {item.observacoes}</p>}
      {item.parecer && <p className="mt-3 rounded-xl bg-sky-400/10 p-3 text-sm text-sky-100"><b>Parecer administrativo:</b> {item.parecer}</p>}
      {!item.obreiroId && item.status !== "Arquivado" && <label className="mt-4 block text-sm text-zinc-400">Parecer, justificativa ou orientação<textarea rows={3} maxLength={2000} value={pareceres[item.id] ?? item.parecer} onChange={(e) => setPareceres((atual) => ({ ...atual, [item.id]: e.target.value }))} className={`mt-1 ${campo}`} /></label>}
      {duplicados[item.id]?.length > 0 && <div className="mt-4 rounded-2xl border border-orange-300/30 bg-orange-300/5 p-4"><h3 className="font-black text-orange-100">Possíveis cadastros existentes</h3><p className="mt-1 text-sm text-zinc-400">Vincule apenas após conferir e-mail, CIM ou CPF.</p><div className="mt-3 grid gap-2">{duplicados[item.id].map((duplicado) => <div key={duplicado.id} className="flex flex-col gap-2 rounded-xl border border-white/10 p-3 sm:flex-row sm:items-center sm:justify-between"><span><b>{duplicado.nome}</b><small className="block text-zinc-400">{duplicado.email || "Sem e-mail"} · CIM {duplicado.cim || "não informado"}</small></span><button type="button" disabled={processando === item.id} onClick={() => void converter(item, duplicado.id)} className="rounded-xl bg-orange-300 px-4 py-2 font-bold text-black">Vincular e complementar</button></div>)}</div></div>}
      <div className="mt-4 grid gap-2 sm:flex sm:flex-wrap sm:justify-end">{!item.obreiroId && <><button disabled={processando === item.id} onClick={() => void movimentar(item, "Em análise")} className="rounded-xl border border-sky-300/30 px-4 py-2 font-bold text-sky-100">Marcar em análise</button><button disabled={processando === item.id} onClick={() => void movimentar(item, "Correção solicitada")} className="rounded-xl border border-orange-300/30 px-4 py-2 font-bold text-orange-100">Solicitar correção</button><button disabled={processando === item.id} onClick={() => void movimentar(item, "Recusado")} className="rounded-xl border border-red-300/30 px-4 py-2 font-bold text-red-100">Recusar</button><button disabled={processando === item.id} onClick={() => void movimentar(item, "Aprovado")} className="rounded-xl bg-emerald-400 px-4 py-2 font-black text-black">Aprovar</button>{item.status === "Aprovado" && <button disabled={processando === item.id} onClick={() => void converter(item)} className="rounded-xl bg-amber-400 px-4 py-2 font-black text-black">Converter em Obreiro</button>}<button disabled={processando === item.id} onClick={() => void movimentar(item, "Arquivado")} className="rounded-xl border border-white/10 px-4 py-2">Arquivar</button></>}{item.obreiroId && <><Link href="/obreiros" className="inline-flex min-h-11 items-center justify-center rounded-xl border border-emerald-300/30 px-4 py-2 font-bold text-emerald-100">Ver Obreiro criado</Link>{podeCriarUsuario && !item.usuarioId && <Link href={`/usuarios?obreiroId=${encodeURIComponent(item.obreiroId)}&preCadastroId=${encodeURIComponent(item.id)}`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-amber-400 px-4 py-2 font-black text-black">Criar usuário de acesso</Link>}</>}</div>
      {processando === item.id && <p className="mt-3 text-right text-sm text-amber-200">Processando com segurança…</p>}</div>
    </details>) : <EmptyState title="Nenhum pré-cadastro encontrado" description="Altere os filtros ou aguarde uma nova solicitação pública." />}</section>
  </div>;
}
