"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Obreiro } from "@/types";
import { carregarObreiros } from "@/lib/obreiros";
import { permissoesPadrao, type PerfilSigma, type PerfilUsuario } from "@/lib/auth";
import { alterarStatusUsuario, atualizarUsuario, convidarUsuario, reenviarConvite } from "@/app/usuarios/actions";

const perfis: PerfilUsuario[] = ["Administrador", "Venerável Mestre", "Secretário", "Tesoureiro", "Chanceler", "Obreiro"];
const rotas = ["/dashboard", "/obreiros", "/secretaria", "/chancelaria", "/tesouraria", "/prestacao-contas", "/configuracoes", "/backup", "/usuarios"];
const vazio = { nome: "", email: "", perfil: "Obreiro" as PerfilUsuario, obreiroId: "", permissoes: permissoesPadrao("Obreiro") };

export function UsuariosClient({ usuarios }: { usuarios: PerfilSigma[] }) {
  const router = useRouter(); const [busca, setBusca] = useState(""); const [obreiros] = useState<Obreiro[]>(() => typeof window === "undefined" ? [] : carregarObreiros()); const [form, setForm] = useState(vazio); const [editando, setEditando] = useState<PerfilSigma | null>(null); const [mensagem, setMensagem] = useState(""); const [enviando, setEnviando] = useState(false);
  const filtrados = useMemo(() => usuarios.filter((u) => `${u.nome} ${u.email} ${u.perfil}`.toLowerCase().includes(busca.toLowerCase())), [usuarios, busca]);
  const ativos = usuarios.filter((u) => u.status === "ativo").length;
  function alterarPermissao(rota: string) { setForm((atual) => ({ ...atual, permissoes: atual.permissoes.includes(rota) ? atual.permissoes.filter((p) => p !== rota) : [...atual.permissoes, rota] })); }
  async function salvar(event: React.FormEvent) { event.preventDefault(); setEnviando(true); setMensagem(""); try { if (editando) await atualizarUsuario({ id: editando.id, nome: form.nome, perfil: form.perfil, obreiroId: form.obreiroId || null, permissoes: form.permissoes }); else await convidarUsuario({ nome: form.nome, email: form.email, perfil: form.perfil, obreiroId: form.obreiroId || null, permissoes: form.permissoes }); setMensagem(editando ? "Usuário atualizado." : "Convite enviado por e-mail."); setEditando(null); setForm(vazio); router.refresh(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar."); } finally { setEnviando(false); } }
  function editar(usuario: PerfilSigma) { setEditando(usuario); setForm({ nome: usuario.nome, email: usuario.email, perfil: usuario.perfil, obreiroId: usuario.obreiro_id ?? "", permissoes: usuario.permissoes }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function acao(callback: () => Promise<void>) { setMensagem(""); try { await callback(); router.refresh(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Operação não concluída."); } }
  return <div className="mt-8 space-y-6"><section className="grid gap-4 md:grid-cols-3">{[["Usuários", usuarios.length], ["Ativos", ativos], ["Convites pendentes", usuarios.filter((u) => u.status === "convite_enviado").length]].map(([titulo, valor]) => <div key={String(titulo)} className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><p className="text-sm text-zinc-400">{titulo}</p><p className="mt-2 text-3xl font-black text-amber-300">{valor}</p></div>)}</section>
    <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h3 className="text-xl font-bold">{editando ? "Editar usuário" : "Convidar usuário"}</h3><form onSubmit={salvar} className="mt-5 grid gap-4 md:grid-cols-2"><input required value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} placeholder="Nome completo" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><input required disabled={!!editando} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="E-mail" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 disabled:opacity-60"/><select value={form.obreiroId} onChange={(e) => { const obreiro = obreiros.find((item) => item.id === e.target.value); setForm({ ...form, obreiroId: e.target.value, nome: obreiro?.nome || form.nome, email: obreiro?.email || form.email }); }} className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"><option value="">Vincular a obreiro (opcional)</option>{obreiros.map((obreiro) => <option key={obreiro.id} value={obreiro.id}>{obreiro.nome}</option>)}</select><select value={form.perfil} onChange={(e) => { const perfil = e.target.value as PerfilUsuario; setForm({ ...form, perfil, permissoes: permissoesPadrao(perfil) }); }} className="rounded-xl border border-white/10 bg-black/20 px-4 py-3">{perfis.map((perfil) => <option key={perfil}>{perfil}</option>)}</select><div className="md:col-span-2"><p className="mb-2 text-sm text-zinc-400">Permissões do módulo</p><div className="flex flex-wrap gap-2">{rotas.map((rota) => <label key={rota} className="rounded-full border border-white/10 px-3 py-2 text-sm"><input className="mr-2" type="checkbox" checked={form.permissoes.includes(rota)} onChange={() => alterarPermissao(rota)}/>{rota}</label>)}</div></div><div className="flex gap-3"><button disabled={enviando} className="rounded-full bg-amber-400 px-5 py-3 font-bold text-black disabled:opacity-60">{enviando ? "Salvando..." : editando ? "Salvar alterações" : "Enviar convite"}</button>{editando && <button type="button" onClick={() => { setEditando(null); setForm(vazio); }} className="rounded-full border border-white/10 px-5 py-3">Cancelar</button>}</div></form>{mensagem && <p className="mt-4 text-sm text-amber-300">{mensagem}</p>}</section>
    <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><h3 className="text-xl font-bold">Acessos cadastrados</h3><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar nome, e-mail ou perfil" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"/></div><div className="mt-5 space-y-3">{filtrados.map((usuario) => <article key={usuario.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/10 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-bold">{usuario.nome}</p><p className="text-sm text-zinc-400">{usuario.email} · {usuario.perfil}</p><p className="mt-1 text-xs text-amber-300">{usuario.status.replace("_", " ")}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => editar(usuario)} className="rounded-full border border-white/10 px-3 py-2 text-sm">Editar</button><button onClick={() => acao(() => reenviarConvite(usuario.email))} className="rounded-full border border-white/10 px-3 py-2 text-sm">{usuario.status === "convite_enviado" ? "Reenviar convite" : "Enviar redefinição"}</button>{usuario.status === "ativo" ? <button onClick={() => acao(() => alterarStatusUsuario(usuario.id, "suspenso"))} className="rounded-full border border-red-400/30 px-3 py-2 text-sm text-red-200">Suspender</button> : <button onClick={() => acao(() => alterarStatusUsuario(usuario.id, "ativo"))} className="rounded-full border border-emerald-400/30 px-3 py-2 text-sm text-emerald-200">Reativar</button>}<button onClick={() => { if (window.confirm("Revogar permanentemente este acesso?")) void acao(() => alterarStatusUsuario(usuario.id, "revogado")); }} className="rounded-full border border-red-400/30 px-3 py-2 text-sm text-red-200">Revogar</button></div></article>)}{!filtrados.length && <p className="py-6 text-center text-zinc-500">Nenhum usuário encontrado.</p>}</div></section>
  </div>;
}
